# Generated by Django 5.1 on 2025-10-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_publicacion', models.DateField()),
                ('isbn', models.CharField(help_text='Formato: XXX-X-XXX-XXXXX-X', max_length=17, unique=True)),
                ('tipo_producto', models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], default='fisico', max_length=10)),
            ],
        ),
    ]
